language: scala
jdk: oraclejdk8
script: sbt ";^^$TRAVIS_SBT_VERSION;validate"

matrix:
  include:
  - env: TRAVIS_SBT_VERSION="0.13.16"
    scala: 2.10.6
  - env: TRAVIS_SBT_VERSION="1.0.2"
    scala: 2.12.4

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  email:
    on_success: never
